# Generated by Django 4.1.6 on 2023-02-12 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ICartApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterprice',
            name='price',
            field=models.CharField(choices=[('> 500', '> 500'), ('500 to 2000', '500 to 2000'), ('2000 to 5000', '2000 to 5000'), ('5000 to 10000', '5000 to 10000'), ('10000 to 50000 <', '10000 to 50000'), ('50000 <', '50000 <')], max_length=60),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('image', models.ImageField(upload_to='ProductImages/images')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('annotations', models.TextField()),
                ('description', models.TextField()),
                ('stock', models.CharField(choices=[('Instock', 'Instock'), ('Out of Stock', 'Out of Stock')], max_length=200)),
                ('status', models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], max_length=200)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICartApp.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICartApp.color')),
                ('filter_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICartApp.filterprice')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICartApp.subcategory')),
            ],
        ),
    ]
