# Generated by Django 4.1.6 on 2023-02-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ICartApp', '0002_alter_filterprice_price_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ProductImages/images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICartApp.product')),
            ],
        ),
    ]
