# Generated by Django 4.1.6 on 2023-02-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICartApp', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old')], default=('Old', 'Old'), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filterprice',
            name='price',
            field=models.CharField(choices=[('> 500', '> 500'), ('500 to 2000', '500 to 2000'), ('2000 to 5000', '2000 to 5000'), ('5000 to 10000', '5000 to 10000'), ('10000 to 50000', '10000 to 50000'), ('50000 <', '50000 <')], max_length=60),
        ),
    ]
